name: Build & Push Images

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_LOGIN }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}


    # frontend
    
    - name: Build frontend
      working-directory: ./front-end-react
      run: docker build -t frontend .
      
    - name: Tag frontend
      working-directory: ./front-end-react
      run: docker tag frontend chavantfou/frontend #:$(date +%s)

    - name: Push frontend
      working-directory: ./front-end-react
      run: docker push chavantfou/frontend #:$(date +%s)


    # order-service

    - name: Build order-service
      working-directory: ./order-service
      run: docker build -t order-service .
      
    - name: Tag order-service
      working-directory: ./order-service
      run: docker tag order-service chavantfou/order-service

    - name: Push order-service
      working-directory: ./order-service
      run: docker push chavantfou/order-service


    # user-service

    - name: Build user-service
      working-directory: ./user-service
      run: docker build -t user-service .
      
    - name: Tag user-service
      working-directory: ./user-service
      run: docker tag user-service chavantfou/user-service

    - name: Push user-service
      working-directory: ./user-service
      run: docker push chavantfou/user-service

